export default defineEventHandler((event) => {
  const path = event.path || ''

  // Only guard API routes.
  if (!path.startsWith('/api/')) return

  // Auth endpoints are public.
  if (path.startsWith('/api/auth/')) return

  // Allow Nitro OpenAPI endpoints (generated by nitro.experimental.openAPI).
  if (path.includes('_openapi')) return

  // Everything else under /api requires an authenticated session.
  if (!event.context.user) {
    throw createError({ statusCode: 401, statusMessage: 'Unauthorized' })
  }
})
