name: Nuxt.js CI

on:
  push:
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest # Specify the runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5 # Action to checkout your code

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      # Set mock DATABASE_URL for Prisma commands
      - name: Set up DATABASE_URL
        run: echo "DATABASE_URL=file:./dev.db" >> $GITHUB_ENV

      - name: Prisma Generate
        run: pnpm prisma generate

      - name: Typecheck
        run: pnpm nuxt typecheck
      - name: Build
        run: pnpm build
